name: Language Recognition

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_syntax_highlighting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git attributes
        run: |
          echo '*.sql linguist-language=sql' >> .gitattributes
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit Git attributes
        run: |
          git add .gitattributes
          git commit -m "Configure SQL language recognition"

      - name: Push Git attributes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
